FROM gcr.io/distroless/static:nonroot

ARG TARGETARCH

COPY linux/${TARGETARCH}/runnerd /usr/local/bin/runnerd

EXPOSE 25500
ENTRYPOINT ["/usr/local/bin/runnerd"]
CMD ["--config", "/etc/runnerd/runnerd.yaml"]
